# Generated by Django 4.2.1 on 2023-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='bio',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='content',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='post',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profilepicture',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
