# Generated by Django 4.2.1 on 2023-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_socialmedia_bio_alter_socialmedia_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='post',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
